LIB=		estdraft
SRCS=		estdraft.c
NOMAN=		#
NOPIC=		yes

NOLINT=			# for NetBSD
MKLINKLIB=	no	# for NetBSD
MKPIC=		no	# for NetBSD

_whereobj:
	@echo ${.OBJDIR}

install:
	@echo -n

.include <bsd.lib.mk>
