name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2     
    - name: Install libevent-dev
      run: sudo apt-get install -y libevent-dev
    - name: Install libestraier-dev
      run: sudo apt-get install -y libestraier-dev
    - name: Install bison
      run: sudo apt-get install -y bison
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
